### PR TITLE
Conf by volume

### PR DESCRIPTION
**Pull request by pazoozooCH**
Hi

I was making a change to your image. Your solution of changing the config files in the running container by looking up the volume with `docker inspect` is not really ideal as I'm using the image in an automated Puppet provisioning context. That means I'd like to be able to specify config changes before I actually start the container.

I changed the config approach by removing the config files from the Dockerfile and adding them to an init script. The init script first copies the default configs from the image, but allows to overwrite them by specifying them in a Volume.

What do you think, could you include these changes in your image?

Cheers Martin

btw It would be nice if you would explicitly tag all your releases. Currently, the latest release only has the tag _latest_ and no version tag which makes it hard to identify in automated setup scripts...

### CODE REVIEW

**Comment by hopsoft** [comment]
I've been thinking about this for a while as this is somewhat related to pull #27 I'm going to be out of town for a while but will review when I get back.

My tagging strategy has been to track along with graphite & phusion's base image. The docker registry tags track the git tags. I'm open to ideas on improving this.

**Comment by pazoozooCH** [comment]
Ok, thanks, just let me know what you think. I tried to leave the existing installation as unchanged as possible. The PR might need some tweaking to avoid overwriting conf files that have been manually changed on restart of the container. I can make these changes if you generally agree on the approach. Maybe you also have some other ideas...

I've already pushed a fork to my docker repo: https://registry.hub.docker.com/u/inftec/graphite/

Maybe you can consider tagging releases with major configurative changes (like this) that don't include a graphite nor phusion change (not sure how often they happen). I would certainly have the graphite version in the tag as this image is primarly about Graphite. Maybe it would be enough to just add another minor version identifier then for non-Graphite updates and describe them in brief changelog section in the README, e.g.;

* v0.9.12
* v0.9.12-b (README: Updated phusion to x.y.z)
* v0.9.12-c (README: Refactored custom configuration handling)

It's certainly always good to use tags so images can be identified, above all when using automation scripts. But it's certainly fine to map master to latest for minor changes and bugfixes.

**Comment by hopsoft** [comment]
I'm using tags in both git & docker. Let me know if you are having problems using tagged versions of the repo or image.

```
GRAPHITE_VERSION-PHUSION_VERSION
v0.9.12-phusion-0.9.15
```

https://github.com/hopsoft/docker-graphite-statsd/tags
https://registry.hub.docker.com/u/hopsoft/graphite-statsd/tags/manage/

**Comment by rodriguezsergio** [comment]
Any chance this will be merged?

**Comment by hopsoft** [comment]
I'm finally getting around to merging this. Will hopefully have it merged with some minor mods later tonight.

**Pull request merged**
